version: "3.9"

services:
  jupyter_book:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: jupyter_book
    container_name: jupyter_book_devcontainer
    volumes:
      - type: bind
        source: ..
        target: /workspace
    tty: true
    stdin_open: true
